# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'configWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QWidget)
import logo_rc

class Ui_mchn_Config(object):
    def setupUi(self, mchn_Config):
        if not mchn_Config.objectName():
            mchn_Config.setObjectName(u"mchn_Config")
        mchn_Config.resize(391, 292)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush)
        brush1 = QBrush(QColor(31, 42, 37, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        mchn_Config.setPalette(palette)
        self.ip_addr_box = QLineEdit(mchn_Config)
        self.ip_addr_box.setObjectName(u"ip_addr_box")
        self.ip_addr_box.setGeometry(QRect(140, 110, 171, 20))
        self.port_no_box = QLineEdit(mchn_Config)
        self.port_no_box.setObjectName(u"port_no_box")
        self.port_no_box.setGeometry(QRect(140, 140, 171, 20))
        self.novaMindSolutions_logo = QLabel(mchn_Config)
        self.novaMindSolutions_logo.setObjectName(u"novaMindSolutions_logo")
        self.novaMindSolutions_logo.setGeometry(QRect(10, 251, 31, 31))
        palette1 = QPalette()
        brush2 = QBrush(QColor(239, 239, 216, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush2)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush2)
        brush3 = QBrush(QColor(120, 120, 120, 255))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush3)
        self.novaMindSolutions_logo.setPalette(palette1)
        self.novaMindSolutions_logo.setPixmap(QPixmap(u":/logoFile/operon.png"))
        self.novaMindSolutions_logo.setScaledContents(True)
        self.novaMindHeading = QLabel(mchn_Config)
        self.novaMindHeading.setObjectName(u"novaMindHeading")
        self.novaMindHeading.setGeometry(QRect(50, 251, 141, 16))
        palette2 = QPalette()
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush2)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush2)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush3)
        self.novaMindHeading.setPalette(palette2)
        font = QFont()
        font.setFamilies([u"Bodoni MT"])
        font.setPointSize(10)
        font.setBold(True)
        self.novaMindHeading.setFont(font)
        self.emailNMS = QLabel(mchn_Config)
        self.emailNMS.setObjectName(u"emailNMS")
        self.emailNMS.setGeometry(QRect(50, 261, 181, 16))
        palette3 = QPalette()
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush2)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush2)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush3)
        self.emailNMS.setPalette(palette3)
        font1 = QFont()
        font1.setFamilies([u"Calibri"])
        font1.setPointSize(8)
        font1.setBold(False)
        self.emailNMS.setFont(font1)
        self.license_resrv_line = QLabel(mchn_Config)
        self.license_resrv_line.setObjectName(u"license_resrv_line")
        self.license_resrv_line.setGeometry(QRect(10, 231, 111, 16))
        palette4 = QPalette()
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush2)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush2)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush3)
        self.license_resrv_line.setPalette(palette4)
        font2 = QFont()
        font2.setFamilies([u"Candara"])
        font2.setPointSize(7)
        font2.setBold(False)
        self.license_resrv_line.setFont(font2)
        self.label = QLabel(mchn_Config)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(250, 250, 131, 16))
        palette5 = QPalette()
        palette5.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush2)
        palette5.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush2)
        palette5.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush3)
        self.label.setPalette(palette5)
        font3 = QFont()
        font3.setFamilies([u"Calibri"])
        font3.setPointSize(10)
        font3.setBold(True)
        self.label.setFont(font3)
        self.ipLabel = QLabel(mchn_Config)
        self.ipLabel.setObjectName(u"ipLabel")
        self.ipLabel.setGeometry(QRect(70, 110, 81, 21))
        palette6 = QPalette()
        brush4 = QBrush(QColor(253, 248, 223, 255))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
        palette6.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush4)
        palette6.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush4)
        brush5 = QBrush(QColor(51, 81, 120, 255))
        brush5.setStyle(Qt.BrushStyle.SolidPattern)
        palette6.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush5)
        self.ipLabel.setPalette(palette6)
        self.portLabel = QLabel(mchn_Config)
        self.portLabel.setObjectName(u"portLabel")
        self.portLabel.setGeometry(QRect(80, 140, 51, 21))
        palette7 = QPalette()
        palette7.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush4)
        palette7.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush4)
        palette7.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush5)
        self.portLabel.setPalette(palette7)
        self.MACHINE_CONFIGURATION = QLabel(mchn_Config)
        self.MACHINE_CONFIGURATION.setObjectName(u"MACHINE_CONFIGURATION")
        self.MACHINE_CONFIGURATION.setGeometry(QRect(30, 20, 331, 41))
        palette8 = QPalette()
        brush6 = QBrush(QColor(220, 232, 192, 255))
        brush6.setStyle(Qt.BrushStyle.SolidPattern)
        palette8.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush6)
        palette8.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush6)
        palette8.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush3)
        self.MACHINE_CONFIGURATION.setPalette(palette8)
        font4 = QFont()
        font4.setFamilies([u"Bodoni MT Black"])
        font4.setPointSize(16)
        font4.setBold(True)
        self.MACHINE_CONFIGURATION.setFont(font4)
        self.FOR_HL7_DATA = QLabel(mchn_Config)
        self.FOR_HL7_DATA.setObjectName(u"FOR_HL7_DATA")
        self.FOR_HL7_DATA.setGeometry(QRect(160, 60, 81, 16))
        palette9 = QPalette()
        palette9.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush6)
        palette9.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush6)
        palette9.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush3)
        self.FOR_HL7_DATA.setPalette(palette9)
        self.confirm_btn = QPushButton(mchn_Config)
        self.confirm_btn.setObjectName(u"confirm_btn")
        self.confirm_btn.setGeometry(QRect(140, 180, 71, 23))
        self.cance_btn = QPushButton(mchn_Config)
        self.cance_btn.setObjectName(u"cance_btn")
        self.cance_btn.setGeometry(QRect(230, 180, 71, 23))

        self.retranslateUi(mchn_Config)

        QMetaObject.connectSlotsByName(mchn_Config)
    # setupUi

    def retranslateUi(self, mchn_Config):
        mchn_Config.setWindowTitle(QCoreApplication.translate("mchn_Config", u"Dialog", None))
        self.novaMindSolutions_logo.setText("")
        self.novaMindHeading.setText(QCoreApplication.translate("mchn_Config", u"OPERON SOLUTIONS", None))
        self.emailNMS.setText(QCoreApplication.translate("mchn_Config", u"operonsolutions@gmail.com", None))
        self.license_resrv_line.setText(QCoreApplication.translate("mchn_Config", u"LICENSE IS RESERVED BY :", None))
        self.label.setText(QCoreApplication.translate("mchn_Config", u"CONTACT : 9878519609", None))
        self.ipLabel.setText(QCoreApplication.translate("mchn_Config", u"IP ADDRESS", None))
        self.portLabel.setText(QCoreApplication.translate("mchn_Config", u"PORT NO.", None))
        self.MACHINE_CONFIGURATION.setText(QCoreApplication.translate("mchn_Config", u"MACHINE CONFIGURATION", None))
        self.FOR_HL7_DATA.setText(QCoreApplication.translate("mchn_Config", u"FOR HL7 DATA", None))
        self.confirm_btn.setText(QCoreApplication.translate("mchn_Config", u"CONFIRM", None))
        self.cance_btn.setText(QCoreApplication.translate("mchn_Config", u"CANCEL", None))
    # retranslateUi

