# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'loginWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QWidget)
import logo_rc

class Ui_loginDialog(object):
    def setupUi(self, loginDialog):
        if not loginDialog.objectName():
            loginDialog.setObjectName(u"loginDialog")
        loginDialog.resize(408, 310)
        palette = QPalette()
        brush = QBrush(QColor(248, 255, 230, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush1 = QBrush(QColor(102, 162, 240, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        brush2 = QBrush(QColor(214, 232, 255, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush2)
        brush3 = QBrush(QColor(158, 197, 247, 255))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush3)
        brush4 = QBrush(QColor(51, 81, 120, 255))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush4)
        brush5 = QBrush(QColor(68, 108, 160, 255))
        brush5.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush5)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush6)
        brush7 = QBrush(QColor(255, 255, 255, 255))
        brush7.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush7)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush6)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush7)
        brush8 = QBrush(QColor(31, 42, 37, 255))
        brush8.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush8)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush6)
        brush9 = QBrush(QColor(178, 208, 247, 255))
        brush9.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush9)
        brush10 = QBrush(QColor(255, 255, 220, 255))
        brush10.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush10)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush6)
        brush11 = QBrush(QColor(0, 0, 0, 128))
        brush11.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush11)
#endif
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush2)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush3)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush4)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush7)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush7)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush8)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush9)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush10)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush11)
#endif
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush2)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush3)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush7)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush8)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush8)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush6)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush10)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush11)
#endif
        loginDialog.setPalette(palette)
        icon = QIcon()
        icon.addFile(u"../../../Downloads/Nova_sol.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        loginDialog.setWindowIcon(icon)
        self.CBC_ANALYSER_SOFTWARE = QLabel(loginDialog)
        self.CBC_ANALYSER_SOFTWARE.setObjectName(u"CBC_ANALYSER_SOFTWARE")
        self.CBC_ANALYSER_SOFTWARE.setGeometry(QRect(50, 40, 321, 41))
        font = QFont()
        font.setFamilies([u"Bodoni MT Black"])
        font.setPointSize(16)
        font.setBold(True)
        self.CBC_ANALYSER_SOFTWARE.setFont(font)
        self.license_resrv_line = QLabel(loginDialog)
        self.license_resrv_line.setObjectName(u"license_resrv_line")
        self.license_resrv_line.setGeometry(QRect(20, 250, 111, 16))
        font1 = QFont()
        font1.setFamilies([u"Candara"])
        font1.setPointSize(7)
        font1.setBold(False)
        self.license_resrv_line.setFont(font1)
        self.usernamLabel = QLabel(loginDialog)
        self.usernamLabel.setObjectName(u"usernamLabel")
        self.usernamLabel.setGeometry(QRect(120, 90, 71, 21))
        palette1 = QPalette()
        brush12 = QBrush(QColor(253, 248, 223, 255))
        brush12.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush12)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush12)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush4)
        self.usernamLabel.setPalette(palette1)
        self.passwordLabel = QLabel(loginDialog)
        self.passwordLabel.setObjectName(u"passwordLabel")
        self.passwordLabel.setGeometry(QRect(120, 120, 71, 20))
        self.usernameBox = QLineEdit(loginDialog)
        self.usernameBox.setObjectName(u"usernameBox")
        self.usernameBox.setGeometry(QRect(190, 90, 113, 20))
        self.passwordBox = QLineEdit(loginDialog)
        self.passwordBox.setObjectName(u"passwordBox")
        self.passwordBox.setGeometry(QRect(190, 120, 113, 20))
        self.versionLabel = QLabel(loginDialog)
        self.versionLabel.setObjectName(u"versionLabel")
        self.versionLabel.setGeometry(QRect(300, 0, 47, 31))
        font2 = QFont()
        font2.setFamilies([u"Impact"])
        font2.setPointSize(10)
        self.versionLabel.setFont(font2)
        self.versionBox = QLineEdit(loginDialog)
        self.versionBox.setObjectName(u"versionBox")
        self.versionBox.setGeometry(QRect(350, 8, 41, 16))
        font3 = QFont()
        font3.setFamilies([u"Imprint MT Shadow"])
        self.versionBox.setFont(font3)
        self.labNameLabel = QLabel(loginDialog)
        self.labNameLabel.setObjectName(u"labNameLabel")
        self.labNameLabel.setGeometry(QRect(10, 10, 91, 16))
        self.novaMindHeading = QLabel(loginDialog)
        self.novaMindHeading.setObjectName(u"novaMindHeading")
        self.novaMindHeading.setGeometry(QRect(60, 270, 141, 16))
        font4 = QFont()
        font4.setFamilies([u"Bodoni MT"])
        font4.setPointSize(10)
        font4.setBold(True)
        self.novaMindHeading.setFont(font4)
        self.novaMindSolutions_logo = QLabel(loginDialog)
        self.novaMindSolutions_logo.setObjectName(u"novaMindSolutions_logo")
        self.novaMindSolutions_logo.setGeometry(QRect(20, 270, 31, 31))
        self.novaMindSolutions_logo.setPixmap(QPixmap(u":/logoFile/operon.png"))
        self.novaMindSolutions_logo.setScaledContents(True)
        self.emailNMS = QLabel(loginDialog)
        self.emailNMS.setObjectName(u"emailNMS")
        self.emailNMS.setGeometry(QRect(60, 280, 181, 16))
        font5 = QFont()
        font5.setFamilies([u"Calibri"])
        font5.setPointSize(8)
        font5.setBold(False)
        self.emailNMS.setFont(font5)
        self.okBtn = QPushButton(loginDialog)
        self.okBtn.setObjectName(u"okBtn")
        self.okBtn.setGeometry(QRect(130, 160, 75, 23))
        self.okBtn.setMouseTracking(False)
        self.okBtn.setAutoFillBackground(False)
        self.okBtn.setAutoDefault(True)
        self.okBtn.setFlat(False)
        self.cancelBtn = QPushButton(loginDialog)
        self.cancelBtn.setObjectName(u"cancelBtn")
        self.cancelBtn.setGeometry(QRect(220, 160, 75, 23))
        self.cancelBtn.setAutoFillBackground(True)
        self.label = QLabel(loginDialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(260, 269, 131, 16))
        font6 = QFont()
        font6.setFamilies([u"Calibri"])
        font6.setPointSize(10)
        font6.setBold(True)
        self.label.setFont(font6)

        self.retranslateUi(loginDialog)

        self.okBtn.setDefault(False)


        QMetaObject.connectSlotsByName(loginDialog)
    # setupUi

    def retranslateUi(self, loginDialog):
        loginDialog.setWindowTitle(QCoreApplication.translate("loginDialog", u"Dialog", None))
        self.CBC_ANALYSER_SOFTWARE.setText(QCoreApplication.translate("loginDialog", u"CBC ANALYZER SOFTWARE", None))
        self.license_resrv_line.setText(QCoreApplication.translate("loginDialog", u"LICENSE IS RESERVED BY :", None))
        self.usernamLabel.setText(QCoreApplication.translate("loginDialog", u"USERNAME :", None))
        self.passwordLabel.setText(QCoreApplication.translate("loginDialog", u"PASSWORD :", None))
        self.usernameBox.setPlaceholderText(QCoreApplication.translate("loginDialog", u"admin", None))
        self.versionLabel.setText(QCoreApplication.translate("loginDialog", u"version : ", None))
        self.versionBox.setText(QCoreApplication.translate("loginDialog", u"1.0", None))
        self.labNameLabel.setText(QCoreApplication.translate("loginDialog", u"\"LAB NAME\"", None))
        self.novaMindHeading.setText(QCoreApplication.translate("loginDialog", u"OPERON SOLUTIONS", None))
        self.novaMindSolutions_logo.setText("")
        self.emailNMS.setText(QCoreApplication.translate("loginDialog", u"operonsolutions@gmail.com", None))
        self.okBtn.setText(QCoreApplication.translate("loginDialog", u"OK", None))
        self.cancelBtn.setText(QCoreApplication.translate("loginDialog", u"CANCEL", None))
        self.label.setText(QCoreApplication.translate("loginDialog", u"CONTACT : 9878519609", None))
    # retranslateUi

